# Site settings
author: Brian Breedlove
title: 
header-img: img/home-bg.png
email: b.breedlove@outlook.com
copyright_name: Brian Breedlove
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Breedlove13

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
